development:
  adapter: postgresql
  database: itunes_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: itunes_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: itunes_production
  pool: 5
  timeout: 5000